### ISSUE TITLE
Match likeness

### ISSUE THREAD

**Issue by BitFros7y** [Kirima2nd/samp-command-guess#2]
How about adding match likeness? That is, how similar is the executed command with guessed one.
Because for me at the moment it suggest /kill for command /test
If i had percentage or some other parameter i would add threshold and just suggest /help instead of guessing command. (and suggesting something completely unrelated)

**Comment by Se8870** [comment]
Oh, it's like adding another parameter/return value which gives how many percentage that is similar with guessed one right?
I mean, something like:

```c
new likeness = Command_Guess(guessCmd, cmdtext);
if (likeness < any_percent)
    // give help
 
// give output
```

**Comment by BitFros7y** [comment]
Yes like that. Actually that example is 100% of what i meant :D

**Comment by Se8870** [comment]
Added, https://github.com/Kirima2nd/samp-command-guess/commit/67ffbab11e90a3063da0cfdea344b72c1357a583
