### ISSUE TITLE
Add y_hooks support or fix SSCANF_OnGameModeInit

### ISSUE THREAD

**Issue by r4sheed** [Kirima2nd/samp-command-guess#3]
There is also 2 extra brackets on this line
https://github.com/Kirima2nd/samp-command-guess/blob/2.x/command-guess.inc#L297

**Comment by Se8870** [comment]
I was planning to do some code refactoring since i was too focused writing for other commands, but thanks for reporting this!

**Comment by Se8870** [comment]
Ok for the extra brackets is now fixed, i don't know about SSCANF_OnGameModeInit problem tbh. Can you show me the server log to investigate about the error? @r4sheed

Because i never encountered such error.

**Comment by Se8870** [comment]
resolved
